name: MonsterFaces
version: 1.0.0012
description: Shows all monsters with a fake hat on their head
authors: [meiskam, silentdojo]

main: com.incraftion.monsterfaces.MonsterFaces
database: false
depend: [ProtocolLib]

commands:
  MonsterFaces:
    description: used for config manipulation
    
permissions:
  monsterfaces:
    description: Gives all MonsterFaces permissions
    children:
      monsterfaces.config: true
  monsterfaces.config:
    description: Allows user to edit, save, or reload configs
    children:
      monsterfaces.config.get: true
      monsterfaces.config.set: true
  monsterfaces.config.get:
    description: Allows user to get configs
    default: op
  monsterfaces.config.set:
    description: Allows user to set or reload configs
    default: op
